version: 2
jobs:
  node-init:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
    
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install NPM
          command: npm i
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
    
  node-test:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
            
      - run:
          name: Eslint
          command: npm run lint

      - run:
          name: Jest
          command: npm run test

      - run:
        name: Codecov
        command: npm run codecov
          
  rn-build-android:
    docker:
      - image: circleci/android:api-28-node
      - image: circleci/node:10.12
      - image: circleci/openjdk:8-jdk
      
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-react-native-{{ arch }}
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          
      - restore_cache:
          key: jars-{{ arch }} 
         
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./AppBuilderTest/android/gradlew 
      
      - run:
          name: Download Dependencies
          command: cd /home/circleci/project/AppBuilderTest/android && ./gradlew androidDependencies
        
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ arch }} 
      
      - run:
          name: Set json
          command: | 
            echo '{"projectBase": "/home/circleci/project/AppBuilderTest","settingFilePath":"/app.json","workspacePath":"test","schemePath":"test","androidParams":[{"buildName":"BUILD_TEST","customParam":"testValue"}],"iosParams":[]}' > setting.json
      
      - run:
          name: Android build
          command: npm run test-android
  
  rn-init:
    docker:
      - image: circleci/node:10.12
      
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-react-native-{{ arch }}
        
      - run:
          name: React native init
          command: |
            if [ ! -d "AppBuilderTest" ] 
            then
              npx react-native init AppBuilderTest --npm
            fi
            
          
      - save_cache:
          key: dependency-cache-react-native-{{ arch }}
          paths:
            - AppBuilderTest
          
  node-build:
    docker:
      - image: circleci/node:10.12
      
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: TSC
          command: npm run build

      - run:
          name: Install PKG
          command: sudo npm i -g pkg
            
      - run:
          name: Binary compile
          command: pkg ./dist/src/bin.js --out-path ./pkg
          
      - store_artifacts:
          path: ./pkg
          
workflows:
  version: 2
  test-build:
    jobs:
      - node-init
      - rn-init:
          requires:
            - node-init
      - rn-build-android:
          requires:
            - node-test
      - node-test:
          requires:
            - rn-init
      - node-build:
          requires:
            - rn-build-android
