version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install npm & pkg
          command: npm i && sudo npm i pkg
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
            
      - run:
          name: Binary compile
          command: pkg . --out-path ./binary_builds
          
      - store_artifacts:
          path: ./binary_builds
