version: 2
jobs:
  node-test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install NPM
          command: npm i
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
            
      - run:
          name: Eslint
          command: ./node_modules/.bin/eslint *.js **/*.js
          
  rn-build-android:
    docker:
      - image: circleci/node:8-browsers
      
    steps:
      - checkout
      
      - run:
          name: Android build
          command: | 
            echo '{ "projectBase": "/home/circleci/project", "androidParams": "[\"{\"buildName\":\"TEST\", \"testVariable\": \"TEST\"}\"]" }' > setting.json
  
  rn-init:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-react-native-{{ arch }}
        
      - run:
          name: React native init
          command: |
            if [ ! -d "AppBuilderTest" ] 
            then
              npx react-native init AppBuilderTest --npm && cd ./AppBuilderTest/android
            fi
            
          
      - save_cache:
          key: dependency-cache-react-native-{{ arch }}
          paths:
            - AppBuilderTest
          
  node-build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install PKG
          command: sudo npm i -g pkg
            
      - run:
          name: Binary compile
          command: pkg . --out-path ./binary_builds
          
      - store_artifacts:
          path: ./binary_builds
          
workflows:
  version: 2
  test-build:
    jobs:
      - rn-init
      - rn-build-android:
          requires:
            - rn-init
      - node-test:
          requires:
            - rn-build-android
      - node-build:
          requires:
            - node-test
