version: 2
jobs:
  node-init:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
    
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install NPM
          command: npm i
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
    
  node-test:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
            
      - run:
          name: Eslint
          command: ./node_modules/.bin/eslint *.js **/*.js
          
  rn-build-android:
    docker:
      - image: circleci/node:10.12
      - image: circleci/android:api-28-node8
      
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Set json
          command: | 
            echo '{"projectBase": "/home/circleci/project","settingFilePath":"/app.json","workspacePath":"test","schemePath":"test","androidParams":[{"buildName":"BUILD_TEST","customParam":"testValue"}],"iosParams":[]}' > setting.json
      - run:
          name: Android build
          command: node ./bin.js android setting.json
            
  
  
  rn-init:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-react-native-{{ arch }}
        
      - run:
          name: React native init
          command: |
            if [ ! -d "AppBuilderTest" ] 
            then
              npx react-native init AppBuilderTest --npm
            fi
            
          
      - save_cache:
          key: dependency-cache-react-native-{{ arch }}
          paths:
            - AppBuilderTest
          
  node-build:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install PKG
          command: sudo npm i -g pkg
            
      - run:
          name: Binary compile
          command: pkg . --out-path ./binary_builds
          
      - store_artifacts:
          path: ./binary_builds
          
workflows:
  version: 2
  test-build:
    jobs:
      - node-init
      - rn-init:
          requires:
            - node-init
      - rn-build-android:
          requires:
            - node-test
      - node-test:
          requires:
            - rn-init
      - node-build:
          requires:
            - rn-build-android
