version: 2
jobs:
  node-test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install NPM
          command: npm i
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
            
      - run:
          name: Eslint
          command: ./node_modules/.bin/eslint *.js **/*.js
          
  rn-init:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "./AppBuilderTest/package.json" }}-{{ arch }}
          paths:
            - ./AppBuilderTest
        
      - run:
          name: React native init
          command: npx react-native init AppBuilderTest && cd ./AppBuilderTest/android
          
      - save_cache:
          key: dependency-cache-{{ checksum "./AppBuilderTest/package.json" }}-{{ arch }}
          paths:
            - ./AppBuilderTest
          
  node-build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ arch }}
      
      - run:
          name: Install PKG
          command: sudo npm i -g pkg
            
      - run:
          name: Binary compile
          command: pkg . --out-path ./binary_builds
          
      - store_artifacts:
          path: ./binary_builds
          
workflows:
  version: 2
  test-build:
    jobs:
      - rn-init
      - node-test:
          requires:
            - rn-init
      - node-build:
          requires:
            - node-test
